##===- gong/lib/AST/Makefile -------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
#
#  This implements the AST library for the go language front-end.
#
##===----------------------------------------------------------------------===##

GONG_LEVEL := ../..
LIBRARYNAME := gongAST

include $(GONG_LEVEL)/Makefile

