##===- gong/lib/Lex/Makefile -------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
#
#  This implements the Lexer library for gong.
#
##===----------------------------------------------------------------------===##

GONG_LEVEL := ../..
include $(GONG_LEVEL)/../../Makefile.config

LIBRARYNAME := gongLex

include $(GONG_LEVEL)/Makefile
