##===- gong/lib/Lex/utf/Makefile ---------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
#
#  plan9's utf library.
#
##===----------------------------------------------------------------------===##

GONG_LEVEL := ../../..

LIBRARYNAME := gongUtf

include $(GONG_LEVEL)/Makefile
