##===- gong/lib/Frontend/Makefile -------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

GONG_LEVEL := ../..
LIBRARYNAME := gongFrontend

include $(GONG_LEVEL)/Makefile
