##===- gong/lib/Basic/Makefile -----------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##
#
#  This implements the Basic library for gong.
#
##===----------------------------------------------------------------------===##

GONG_LEVEL := ../..
LIBRARYNAME := gongBasic

include $(GONG_LEVEL)/Makefile
