##===- gong/lib/Sema/Makefile ------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
#
#  This implements the semantic analyzer and AST builder library for the 
#  go language front-end.
#
##===----------------------------------------------------------------------===##

GONG_LEVEL := ../..
LIBRARYNAME := gongSema

include $(GONG_LEVEL)/Makefile


